### PR TITLE
Added a changeTexture method on GLOW.Texture

### PR DESCRIPTION
**Pull request by subblue**
To easily swap images on existing texture objects

### CODE REVIEW

**Comment by subblue** [comment]
Ok, renamed to swapTexture. I'll let you change the other delete ... statements throughout GLOW. What is the issue with V8 and delete? I've not heard of that before.

**Comment by subblue** [comment]
Ahh, found something about 'delete' here: http://kendsnyder.com/posts/chrome-v8-creators-with-and-delete-are-dog-slow

**Comment by empaempa** [comment]
Yup, and there's a great Google IO on breaking the speed limits of JS. It's one of the V8-guys giving some insight to the workings of V8. Great talk, try googling it :)

**Comment by subblue** [comment]
Found it: http://www.youtube.com/watch?v=UJPdhx5zTaw
Very interesting and impressive how good V8 is getting. Thanks for the tip!

**Pull request merged**
